<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5k4vsr4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5k4vsr4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5k4vsr4.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5k4vsr4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5k4vsr4\appDevDebugProjectContainer([
    'container.build_hash' => '5k4vsr4',
    'container.build_id' => '8a0f8f67',
    'container.build_time' => 1607778527,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5k4vsr4');
