<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIrvlcn3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIrvlcn3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIrvlcn3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIrvlcn3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIrvlcn3\appProdProjectContainer([
    'container.build_hash' => 'Irvlcn3',
    'container.build_id' => '434f1ec8',
    'container.build_time' => 1607862640,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIrvlcn3');
