<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xmntpj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xmntpj/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5xmntpj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5xmntpj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5xmntpj\appProdProjectContainer([
    'container.build_hash' => '5xmntpj',
    'container.build_id' => '8c10bbb3',
    'container.build_time' => 1607733273,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xmntpj');
